## Nebraska roster scrape

In [1]:
from urllib.request import urlopen
import pandas as pd

In [2]:
from bs4 import BeautifulSoup

In [3]:
url = 'https://huskers.com/sports/womens-soccer/roster/2021'

In [4]:
page = urlopen(url)
html = page.read().decode('utf-8')
soup = BeautifulSoup(html, "html.parser")

In [5]:
nebraska_roster_21 = pd.DataFrame()

In [6]:
last_names = soup.find_all('span',{'class':"sidearm-roster-player-last-name"})
first_names = soup.find_all('span',{'class':"sidearm-roster-player-first-name"})
player_classes = soup.find_all('span',{'class':"sidearm-roster-player-academic-year"})

In [7]:
lname_list = []
for last_name in last_names:
    lname_list.append(last_name.text)
    
fname_list = []
for first_name in first_names:
    fname_list.append(first_name.text)
    
class_list = []
for player_class in player_classes:
    class_list.append(player_class.text)

In [8]:
class_list = class_list[70:]
lname_list = lname_list[:35]
fname_list = fname_list[:35]

In [9]:
len(class_list)

35

In [10]:
nebraska_roster_21['last_name'] = lname_list
nebraska_roster_21['first_name'] = fname_list
nebraska_roster_21['class'] = class_list

In [11]:
nebraska_roster_21['class'].value_counts(normalize=True)

Sr.    0.314286
Fr.    0.314286
So.    0.257143
Jr.    0.114286
Name: class, dtype: float64

In [12]:
20/35

0.5714285714285714

### Mizzou Schedule Scrape

In [13]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

In [14]:
years = []
for year in range(1996,2016):
    years.append(str(year))

In [15]:
base_schedule_url = 'https://mutigers.com/sports/womens-soccer/schedule/'
schedule_urls = []
for year in years:
    miz_schedule_url = base_schedule_url+year
    schedule_urls.append(miz_schedule_url)

In [16]:
print(schedule_urls)

['https://mutigers.com/sports/womens-soccer/schedule/1996', 'https://mutigers.com/sports/womens-soccer/schedule/1997', 'https://mutigers.com/sports/womens-soccer/schedule/1998', 'https://mutigers.com/sports/womens-soccer/schedule/1999', 'https://mutigers.com/sports/womens-soccer/schedule/2000', 'https://mutigers.com/sports/womens-soccer/schedule/2001', 'https://mutigers.com/sports/womens-soccer/schedule/2002', 'https://mutigers.com/sports/womens-soccer/schedule/2003', 'https://mutigers.com/sports/womens-soccer/schedule/2004', 'https://mutigers.com/sports/womens-soccer/schedule/2005', 'https://mutigers.com/sports/womens-soccer/schedule/2006', 'https://mutigers.com/sports/womens-soccer/schedule/2007', 'https://mutigers.com/sports/womens-soccer/schedule/2008', 'https://mutigers.com/sports/womens-soccer/schedule/2009', 'https://mutigers.com/sports/womens-soccer/schedule/2010', 'https://mutigers.com/sports/womens-soccer/schedule/2011', 'https://mutigers.com/sports/womens-soccer/schedule/2012', 'https://mutigers.com/sports/womens-soccer/schedule/2013', 'https://mutigers.com/sports/womens-soccer/schedule/2014', 'https://mutigers.com/sports/womens-soccer/schedule/2015']

In [17]:
miz_hist_schedule = pd.DataFrame(index=None)
opponent_list = []
date_list = []
result_list = []    
year_list = []
for schedule_url in schedule_urls:
    # empty lists

    
    # Set up parser
    page = urlopen(schedule_url)
    html = page.read().decode('utf-8')
    soup = BeautifulSoup(html,"html.parser")
    
    # pull info
    otags = soup.find_all('div',{"class":'sidearm-schedule-game-opponent-name'})
    dtags = soup.find_all('div',{"class":'sidearm-schedule-game-opponent-date'})
    rtags = soup.find_all('div',{'class':'sidearm-schedule-game-result'})
    
    # get result tag
    for rtag in rtags:
        game_result = rtag.find('span')
        if game_result:
            game_results = rtag.text
            
            #store names
            result_list.append(game_results.strip().replace('\n'," "))
            print(game_results.strip().replace('\n'," ")+", year: "+schedule_url[-4:])
            
    # get opponent tag
    for otag in otags:
        opponent_name = otag.find('a')
        if opponent_name:
            opponent_names = otag.text
            
            # store names
            opponent_list.append(opponent_names.strip().replace("\n"," "))
            
            # print(opponent_names.strip())
        year_list.append(schedule_url[-4:])
    # get date tag
    for dtag in dtags:
        game_date = dtag.find('span')
        if game_date:
            game_dates = dtag.text
            
            # store names
            date_list.append(game_dates.strip().replace("\n"," "))
            # print(game_dates.strip())

L, 4-2, year: 1996
L, 2-1, year: 1996
L, 2-0, year: 1996
W, 1-0, year: 1996
L, 6-0, year: 1996
L, 2-0, year: 1996
W, 2-1 OT, year: 1996
L, 4-1, year: 1996
L, 3-1, year: 1996
L, 5-1, year: 1996
L, 4-0, year: 1996
W, 3-0, year: 1996
L, 8-2, year: 1996
W, 3-1, year: 1996
W, 4-2, year: 1996
L, 2-1, year: 1996
L, 3-0, year: 1996
L, 2-1, year: 1996
W, 3-2, year: 1996
L, 2-1, year: 1996
L, 5-1, year: 1997
L, 4-1, year: 1997
W, 4-1, year: 1997
L, 5-2, year: 1997
L, 5-0, year: 1997
L, 4-3, year: 1997
W, 1-0, year: 1997
L, 2-0, year: 1997
W, 1-0, year: 1997
L, 4-0, year: 1997
L, 4-3 OT, year: 1997
L, 3-1, year: 1997
W, 6-3, year: 1997
W, 3-1, year: 1997
W, 2-0, year: 1997
L, 6-0, year: 1997
W, 3-0, year: 1997
L, 2-1, year: 1997
L, 3-1, year: 1997
W, 7-0, year: 1998
L, 1-0, year: 1998
W, 7-1, year: 1998
W, 2-0, year: 1998
T, 1-1, year: 1998
L, 2-0, year: 1998
L, 4-1, year: 1998
W, 3-2, year: 1998
W, 5-3, year: 1998
L, 1-0, year: 1998
W, 5-1, year: 1998
W, 3-2, year: 1998
W, 7-2, year: 1998
L, 3-1, year: 1998
L, 2-1, year: 1998
L, 1-0, year: 1998
L, 2-1, year: 1998
W, 6-1, year: 1998
W, 3-1, year: 1998
W, 3-2, year: 1998
L, 4-0, year: 1998
W, 5-1, year: 1999
L, 2-1, year: 1999
W, 6-2, year: 1999
W, 2-1, year: 1999
W, 4-1, year: 1999
W, 4-0, year: 1999
W, 3-2, year: 1999
W, 3-1, year: 1999
L, 2-1, year: 1999
W, 6-0, year: 1999
L, 4-1, year: 1999
W, 3-1, year: 1999
W, 2-0, year: 1999
W, 3-0, year: 1999
W, 4-3, year: 1999
L, 5-1, year: 1999
L, 5-2, year: 1999
T, 0-0 2OT, year: 1999
L, 5-1, year: 1999
W, 4-1, year: 1999
W, 5-3, year: 1999
W, 2-1, year: 1999
L, 2-1, year: 1999
L, 3-2 4OT, year: 1999
, year: 2000
W, 4-1, year: 2000
L, 2-1, year: 2000
W, 2-1, year: 2000
W, 2-0, year: 2000
L, 3-2 OT, year: 2000
L, 7-0, year: 2000
W, 2-1, year: 2000
L, 2-1, year: 2000
W, 2-0, year: 2000
W, 1-0, year: 2000
L, 2-0, year: 2000
L, 1-0, year: 2000
W, 2-0, year: 2000
W, 3-1, year: 2000
L, 4-1, year: 2000
L, 3-1, year: 2000
L, 2-1, year: 2000
W, 5-1, year: 2000
W, 4-1, year: 2000
L, 4-3, year: 2000
W, 3-2, year: 2001
W, 1-0, year: 2001
W, 4-0, year: 2001
W, 2-0, year: 2001
W, 6-1, year: 2001
L, 3-2, year: 2001
L, 7-0, year: 2001
W, 3-2, year: 2001
L, 2-1, year: 2001
L, 5-1, year: 2001
W, 1-0, year: 2001
W, 2-0, year: 2001
W, 4-1, year: 2001
L, 1-0, year: 2001
L, 5-2, year: 2001
W, 5-2, year: 2001
W, 12-0, year: 2001
L, 2-0, year: 2001
W, 3-1, year: 2001
W, 1-0 OT, year: 2001
L, 1-0 OT, year: 2001
W, 3-2, year: 2002
L, 2-1, year: 2002
W, 2-1 2OT, year: 2002
L, 2-1 2OT, year: 2002
T, 2-2 2OT, year: 2002
W, 1-0, year: 2002
W, 3-1, year: 2002
W, 1-0, year: 2002
W, 3-1, year: 2002
L, 2-1 1OT, year: 2002
L, 4-0, year: 2002
T, 2-2 2OT, year: 2002
W, 5-1, year: 2002
W, 4-3, year: 2002
L, 2-0, year: 2002
W, 5-1, year: 2002
W, 3-0, year: 2002
W, 5-1, year: 2002
L, 5-3, year: 2002
L, 2-1 OT, year: 2002
W, 2-0, year: 2002
L, 1-0, year: 2002
W, 3-0, year: 2003
W, 2-0, year: 2003
W, 2-1, year: 2003
W, 3-1, year: 2003
L, 1-0, year: 2003
L, 2-1 OT, year: 2003
W, 3-2 OT, year: 2003
L, 4-0, year: 2003
L, 3-2, year: 2003
L, 3-1, year: 2003
W, 1-0, year: 2003
L, 2-1 OT, year: 2003
T, 1-1 2OT, year: 2003
L, 2-0, year: 2003
L, 2-1, year: 2003
W, 5-4 OT, year: 2003
W, 2-1, year: 2003
L, 3-1, year: 2003
W, 4-3, year: 2003
W, 2-0, year: 2003
W, 3-2, year: 2003
L, 3-2 2OT, year: 2003
W, 1-0, year: 2003
L, 2-0, year: 2003
W, 2-1 OT, year: 2004
L, 4-1, year: 2004
L, 2-1, year: 2004
W, 1-0, year: 2004
L, 1-0, year: 2004
T, 2-2, year: 2004
L, 1-0, year: 2004
W, 2-1, year: 2004
W, 2-1 2OT, year: 2004
L, 3-1, year: 2004
L, 2-1, year: 2004
W, 1-0, year: 2004
L, 3-1, year: 2004
L, 2-0, year: 2004
W, 2-1, year: 2004
L, 6-0, year: 2004
W, 4-3, year: 2004
W, 3-2, year: 2004
W, 5-2, year: 2004
L, 2-1 OT, year: 2004
T, 5-5, year: 2005
L, 2-0, year: 2005
T, 0-0, year: 2005
W, 2-0, year: 2005
W, 2-1, year: 2005
W, 7-0, year: 2005
W, 5-0, year: 2005
Cancelled, year: 2005
W, 1-0, year: 2005
L, 1-0, year: 2005
L, 3-2, year: 2005
W, 2-1, year: 2005
T, 1-1 2OT, year: 2005
L, 3-0, year: 2005
T, 1-1 2OT, year: 2005
W, 3-0, year: 2005
L, 3-2, year: 2005
W, 4-1, year: 2005
L, 4-1, year: 2005
W, 1-0, year: 2005
L, 3-2 2OT, year: 2005
L, 3-1, year: 2005
T, 2-2, year: 2006
W, 2-0, year: 2006
W, 5-0, year: 2006
W, 4-0, year: 2006
W, 1-0, year: 2006
W, 3-0, year: 2006
W, 3-2, year: 2006
W, 2-1, year: 2006
L, 1-0, year: 2006
L, 2-0, year: 2006
W, 3-2 OT, year: 2006
L, 3-1, year: 2006
L, 3-0, year: 2006
L, 3-2, year: 2006
L, 2-0, year: 2006
W, 3-0, year: 2006
L, 4-0, year: 2006
L, 1-0, year: 2006
L, 4-2, year: 2006
W, 2-1 2OT, year: 2006
W, 5-0, year: 2007
T, 1-1, year: 2007
W, 3-1, year: 2007
W, 5-2, year: 2007
W, 2-0, year: 2007
W, 3-0, year: 2007
L, 3-2, year: 2007
L, 2-1, year: 2007
W, 4-0, year: 2007
W, 6-2, year: 2007
W, 3-2 2OT, year: 2007
W, 4-2, year: 2007
W, 2-0, year: 2007
W, 3-0, year: 2007
L, 2-1 OT, year: 2007
L, 3-2 OT, year: 2007
W, 2-0, year: 2007
L, 1-0 OT, year: 2007
W, 3-1, year: 2007
L, 2-1, year: 2007
W, 4-3 2OT, year: 2007
L, 4-1, year: 2007
T, 1-1, year: 2007
L, 1-0 2OT, year: 2007
T, 1-1, year: 2008
W, 5-0, year: 2008
L, 2-1 OT, year: 2008
W, 1-0, year: 2008
L, 3-0, year: 2008
W, 3-0, year: 2008
W, 3-0, year: 2008
W, 2-1, year: 2008
W, 2-1, year: 2008
W, 3-0, year: 2008
L, 3-2 2OT, year: 2008
W, 1-0, year: 2008
W, 2-0, year: 2008
W, 2-0, year: 2008
L, 3-2 OT, year: 2008
W, 6-1, year: 2008
W, 3-0, year: 2008
W, 2-0, year: 2008
L, 2-1, year: 2008
W, 6-0, year: 2008
W, 3-1, year: 2008
T, 1-1 2OT, year: 2008
W, 1-0, year: 2008
W, 2-0, year: 2008
T, 1-1 3-4 SO, year: 2008
W, 3-2, year: 2009
W, 2-0, year: 2009
L, 1-0, year: 2009
W, 7-1, year: 2009
L, 4-1, year: 2009
W, 2-1, year: 2009
T, 1-1 2OT, year: 2009
L, 1-0, year: 2009
L, 5-0, year: 2009
W, 8-0, year: 2009
W, 3-2, year: 2009
T, 1-1 2OT, year: 2009
T, 4-4 2OT, year: 2009
W, 1-0 OT, year: 2009
W, 2-1, year: 2009
W, 5-0, year: 2009
W, 1-0 2OT, year: 2009
W, 3-1, year: 2009
W, 5-0, year: 2009
L, 3-2, year: 2009
W, 3-2 OT, year: 2009
L, 3-2, year: 2009
T, 2-2, year: 2010
Canceled, year: 2010
L, 3-2, year: 2010
L, 3-1, year: 2010
L, 6-1, year: 2010
T, 1-1 2OT, year: 2010
T, 1-1, year: 2010
W, 4-0, year: 2010
W, 3-2 2OT, year: 2010
L, 3-2, year: 2010
W, 4-1, year: 2010
L, 3-1, year: 2010
W, 2-1, year: 2010
W, 1-0, year: 2010
L, 4-2, year: 2010
L, 1-0, year: 2010
L, 4-2, year: 2010
W, 2-0, year: 2010
W, 5-2, year: 2010
L, 5-0, year: 2010
L, 4-1, year: 2010
T, 1-1, year: 2011
L, 2-1, year: 2011
W, 4-1, year: 2011
W, 1-0, year: 2011
W, 4-2, year: 2011
W, 3-0, year: 2011
W, 2-0, year: 2011
W, 1-0, year: 2011
W, 1-0, year: 2011
L, 2-0, year: 2011
W, 3-0, year: 2011
L, 1-0, year: 2011
L, 2-0, year: 2011
W, 1-0, year: 2011
L, 2-1, year: 2011
W, 4-0, year: 2011
L, 3-1, year: 2011
W, 5-2, year: 2011
W, 3-2, year: 2011
L, 1-0, year: 2011
T, 2-2 4-3 PKs, year: 2011
L, 3-0, year: 2011
, year: 2012
W, 5-1, year: 2012
W, 2-0, year: 2012
W, 3-2, year: 2012
W, 4-1, year: 2012
W, 2-0, year: 2012
L, 1-0 OT, year: 2012
W, 2-0, year: 2012
W, 1-0, year: 2012
W, 2-1, year: 2012
W, 2-0, year: 2012
W, 2-1, year: 2012
L, 1-0, year: 2012
W, 2-1 OT, year: 2012
W, 2-0, year: 2012
L, 2-1, year: 2012
W, 2-1, year: 2012
L, 2-1, year: 2012
L, 3-1, year: 2012
L, 2-1 OT, year: 2012
W, 2-1, year: 2012
L, 3-0, year: 2012
T, 1-1 0-3 SO, year: 2012
W, 3-2, year: 2013
W, 5-1, year: 2013
L, 2-1 OT, year: 2013
W, 4-0, year: 2013
W, 3-0, year: 2013
L, 2-1, year: 2013
L, 2-1 OT, year: 2013
W, 3-0, year: 2013
L, 3-2, year: 2013
W, 3-1, year: 2013
L, 1-0, year: 2013
W, 1-0, year: 2013
T, 1-1 2OT, year: 2013
L, 2-1, year: 2013
L, 1-0, year: 2013
W, 2-1, year: 2013
T, 1-1 2OT, year: 2013
W, 2-1 2OT, year: 2013
T, 1-1 2OT, year: 2013
L, 2-1 OT, year: 2013
L, 4-0, year: 2013
W, 2-1, year: 2014
T, 0-0 2OT, year: 2014
L, 3-2, year: 2014
W, 2-1 OT, year: 2014
W, 3-1, year: 2014
T, 0-0 2OT, year: 2014
W, 1-0, year: 2014
W, 4-3 2OT, year: 2014
W, 3-1, year: 2014
W, 3-1, year: 2014
W, 1-0, year: 2014
L, 3-1, year: 2014
W, 2-1, year: 2014
W, 2-0, year: 2014
L, 3-2, year: 2014
W, 2-0, year: 2014
L, 1-0, year: 2014
T, 3-3 2OT, year: 2014
L, 3-0, year: 2014
W, 2-1, year: 2014
L, 2-1, year: 2014
W, 3-1, year: 2014
L, 1-0 OT, year: 2014
T, 0-0, year: 2015
T, 1-1, year: 2015
W, 2-0, year: 2015
T, 1-1 2OT, year: 2015
L, 1-0, year: 2015
W, 3-2 2OT, year: 2015
T, 0-0 2OT, year: 2015
T, 0-0, year: 2015
W, 2-1, year: 2015
L, 1-0, year: 2015
L, 1-0, year: 2015
W, 3-1, year: 2015
T, 1-1, year: 2015
W, 2-1, year: 2015
L, 2-1, year: 2015
W, 2-0, year: 2015
W, 3-1, year: 2015
W, 2-1 OT, year: 2015
W, 1-0, year: 2015
T, 1-1, year: 2015
L, 2-1, year: 2015

In [18]:
len(opponent_list)

436

In [19]:
len(year_list)

436

In [20]:
miz_hist_schedule['opponent'] = opponent_list
miz_hist_schedule['game_full_date'] = date_list
miz_hist_schedule['game_year'] = year_list
miz_hist_schedule['game_result'] = result_list

miz_hist_schedule[['game_date','game_full_date']] = miz_hist_schedule['game_full_date'].str.split("(",expand=True)
miz_hist_schedule[['game_day_of_week','game_time']] = miz_hist_schedule['game_full_date'].str.split(")",expand=True)
miz_hist_schedule[['game_result','game_score']] = miz_hist_schedule['game_result'].str.split(',',expand=True)

ValueError: Columns must be same length as key

In [ ]:
miz_hist_schedule

In [ ]:
miz_hist_schedule = miz_hist_schedule.drop(columns = ['game_full_date'])

In [ ]:
miz_hist_schedule.head(235)

In [ ]:
miz_hist_schedule['game_day_of_week'].value_counts()

In [ ]:
miz_hist_schedule.to_csv('/Users/gcdyw9/Documents/github_python/MSM_python/kcou/miz_hist_schedule.csv')

In [ ]:
pd.crosstab(index=miz_hist_schedule['game_day_of_week'],columns=miz_hist_schedule['game_result'],normalize=False)

In [ ]:
pd.crosstab(index=miz_hist_schedule['game_day_of_week'],columns=miz_hist_schedule['game_result'],normalize='index')

In [ ]:
9/29

In [ ]:
miz_hist_schedule_2016 = pd.DataFrame()
opponent_list_2016 = []
date_list_2016 = []
result_list_2016 = []    
year_list_2016 = []

url_2016 = 'https://mutigers.com/sports/womens-soccer/schedule/2016'
# Set up parser
page_2016 = urlopen(url_2016)
html_2016 = page_2016.read().decode('utf-8')
soup_2016 = BeautifulSoup(html_2016,"html.parser")

# pull info
otags = soup_2016.find_all('div',{"class":'sidearm-schedule-game-opponent-name'})
dtags = soup_2016.find_all('div',{"class":'sidearm-schedule-game-opponent-date'})
rtags = soup_2016.find_all('div',{'class':'sidearm-schedule-game-result'})

# get result tag
for rtag in rtags:
    game_result = rtag.find('span')
    if game_result:
        game_results = rtag.text

        #store names
        result_list_2016.append(game_results.strip().replace('\n'," "))
        print(game_results.strip().replace('\n'," ")+", year: "+schedule_url[-4:])

# get opponent tag
for otag in otags:
    opponent_name = otag.find('a')
    if opponent_name:
        opponent_names = otag.text

        # store names
        opponent_list_2016.append(opponent_names.strip().replace("\n"," "))

        # print(opponent_names.strip())
    year_list_2016.append(url_2016[-4:])
# get date tag
for dtag in dtags:
    game_date = dtag.find('span')
    if game_date:
        game_dates = dtag.text

        # store names
        date_list_2016.append(game_dates.strip().replace("\n"," "))
        # print(game_dates.strip())

In [ ]:
opponent_list_2016

In [ ]:
len(date_list_2016)

In [ ]:
result_list_2016.insert(0,'Canceled')

In [ ]:
result_list_2016

In [ ]:
results_2016.append(result_list_2016)

In [ ]:
len(result_list_2016)

In [ ]:
miz_hist_schedule_2016['opponent'] = opponent_list_2016
miz_hist_schedule_2016['game_full_date'] = date_list_2016
miz_hist_schedule_2016['game_year'] = year_list_2016
miz_hist_schedule_2016['game_result'] = result_list_2016

miz_hist_schedule_2016[['game_date','game_full_date']] = miz_hist_schedule_2016['game_full_date'].str.split("(",expand=True)
miz_hist_schedule_2016[['game_day_of_week','game_time']] = miz_hist_schedule_2016['game_full_date'].str.split(")",expand=True)
miz_hist_schedule_2016[['game_result','game_score']] = miz_hist_schedule_2016['game_result'].str.split(',',expand=True)

In [ ]:
miz_hist_schedule_2016
miz_hist_schedule_2016 = miz_hist_schedule_2016.drop(columns = ['game_full_date'])

In [ ]:
dummy_df = miz_hist_schedule_2016.append(miz_hist_schedule, ignore_index=True)

In [ ]:
dummy_df

In [ ]:
pd.crosstab(index=dummy_df['game_day_of_week'],columns=dummy_df['game_result'],normalize=False)

In [21]:
pd.crosstab(index=dummy_df['game_day_of_week'],columns=dummy_df['game_result'],normalize='index')

NameError: name 'dummy_df' is not defined

In [ ]:
pd.crosstab(index=miz_hist_schedule_2016['game_day_of_week'],columns=miz_hist_schedule_2016['game_result'],normalize=False)

In [22]:
dummy_df['game_year'].value_counts()

NameError: name 'dummy_df' is not defined

### Stef Golan vs Nebraska scrape

In [23]:
years = []
for year in range(2012,2020):
    years.append(str(year))

In [24]:
base_schedule_url = 'https://gophersports.com/sports/womens-soccer/schedule/'
schedule_urls = []
for year in years:
    umn_schedule_url = base_schedule_url+year
    schedule_urls.append(umn_schedule_url)

In [25]:
print(schedule_urls)

['https://gophersports.com/sports/womens-soccer/schedule/2012', 'https://gophersports.com/sports/womens-soccer/schedule/2013', 'https://gophersports.com/sports/womens-soccer/schedule/2014', 'https://gophersports.com/sports/womens-soccer/schedule/2015', 'https://gophersports.com/sports/womens-soccer/schedule/2016', 'https://gophersports.com/sports/womens-soccer/schedule/2017', 'https://gophersports.com/sports/womens-soccer/schedule/2018', 'https://gophersports.com/sports/womens-soccer/schedule/2019']

In [26]:
umn_hist_schedule = pd.DataFrame(index=None)
opponent_list = []
date_list = []
result_list = []    
year_list = []
for schedule_url in schedule_urls:
    # empty lists

    
    # Set up parser
    page = urlopen(schedule_url)
    html = page.read().decode('utf-8')
    soup = BeautifulSoup(html,"html.parser")
    
    # pull info
    otags = soup.find_all('div',{"class":'sidearm-schedule-game-opponent-name'})
    dtags = soup.find_all('div',{"class":'sidearm-schedule-game-opponent-date'})
    rtags = soup.find_all('div',{'class':'sidearm-schedule-game-result'})
    
    # get result tag
    for rtag in rtags:
        game_result = rtag.find('span')
        if game_result:
            game_results = rtag.text
            
            #store names
            result_list.append(game_results.strip().replace('\n'," "))
            print(game_results.strip().replace('\n'," ")+", year: "+schedule_url[-4:])
            
    # get opponent tag
    for otag in otags:
        opponent_name = otag.find('a')
        if opponent_name:
            opponent_names = otag.text
            
            # store names
            opponent_list.append(opponent_names.strip().replace("\n"," "))
            
            # print(opponent_names.strip())
        year_list.append(schedule_url[-4:])
    # get date tag
    for dtag in dtags:
        game_date = dtag.find('span')
        if game_date:
            game_dates = dtag.text
            
            # store names
            date_list.append(game_dates.strip().replace("\n"," "))
            # print(game_dates.strip())

W, 4-0, year: 2012
L, 2-3, year: 2012
W, 2-1 OT, year: 2012
L, 2-3 2OT, year: 2012
W, 4-1, year: 2012
W, 7-0, year: 2012
W, 1-0, year: 2012
L, 0-1 OT, year: 2012
W, 3-0, year: 2012
L, 1-2 OT, year: 2012
L, 0-1, year: 2012
W, 1-0, year: 2012
W, 3-2, year: 2012
L, 3-4, year: 2012
T, 0-0 2OT, year: 2012
W, 3-0, year: 2012
W, 1-0, year: 2012
L, 0-2, year: 2012
W, 5-1, year: 2012
W, 4-2, year: 2012
T, 2-2, year: 2012
W, 3-2, year: 2013
W, 2-1, year: 2013
W, 4-1, year: 2013
W, 4-0, year: 2013
W, 1-0, year: 2013
W, 2-1, year: 2013
W, 2-1, year: 2013
L, 0-2, year: 2013
W, 3-0, year: 2013
L, 0-1, year: 2013
L, 0-3, year: 2013
W, 1-0, year: 2013
T, 0-0, year: 2013
W, 1-0, year: 2013
L, 0-2, year: 2013
T, 2-2, year: 2013
L, 0-1, year: 2013
W, 1-0 2OT, year: 2013
W, 2-1, year: 2013
L, 1-3, year: 2013
L, 1-4, year: 2013
L, 0-3, year: 2013
W, 3-0, year: 2014
W, 10-0, year: 2014
L, 1-4, year: 2014
W, 1-0, year: 2014
W, 2-0, year: 2014
L, 2-3, year: 2014
L, 1-3, year: 2014
L, 1-2, year: 2014
W, 1-0, year: 2014
L, 0-1, year: 2014
W, 1-0, year: 2014
W, 2-1, year: 2014
L, 0-1, year: 2014
T, 1-1, year: 2014
W, 3-1, year: 2014
W, 2-1, year: 2014
L, 1-4, year: 2014
W, 1-0, year: 2014
W, 2-0, year: 2014
L, 0-1, year: 2014
W, 1-0, year: 2014
L, 0-1, year: 2014
W, 8-0, year: 2015
W, 3-0, year: 2015
T, 0-0 2OT, year: 2015
W, 1-0, year: 2015
L, 0-1, year: 2015
W, 2-1 OT, year: 2015
T, 0-0 2OT, year: 2015
W, 1-0, year: 2015
W, 9-1, year: 2015
W, 2-1, year: 2015
W, 1-0, year: 2015
W, 3-1, year: 2015
W, 3-1, year: 2015
L, 0-1, year: 2015
W, 3-0, year: 2015
W, 2-0, year: 2015
L, 0-1, year: 2015
T, 0-0, year: 2015
L, 1-3, year: 2015
L, 1-3, year: 2015
L, 1-4, year: 2015
W, 5-0, year: 2015
L, 0-1, year: 2015
T, 0-0, year: 2016
W, 2-1, year: 2016
W, 3-0, year: 2016
W, 3-0, year: 2016
W, 3-0, year: 2016
W, 5-0, year: 2016
L, 0-1, year: 2016
L, 1-4, year: 2016
W, 2-1, year: 2016
T, 1-1, year: 2016
W, 3-0, year: 2016
W, 3-0, year: 2016
W, 2-0, year: 2016
L, 0-1 OT, year: 2016
W, 3-0, year: 2016
W, 3-0, year: 2016
W, 2-1, year: 2016
T, 0-0 2OT, year: 2016
T, 0-0 2OT, year: 2016
W, 6-0, year: 2016
W, 3-1, year: 2016
W, 1-0, year: 2016
W, 2-1, year: 2016
T, 0-0 2OT, year: 2016
W, 1-0, year: 2017
W, 2-0, year: 2017
T, 0-0 2OT, year: 2017
W, 3-0, year: 2017
T, 1-1, year: 2017
W, 6-1, year: 2017
L, 0-1, year: 2017
W, 1-0 2OT, year: 2017
W, 5-0, year: 2017
L, 0-1 OT, year: 2017
T, 2-2 2OT, year: 2017
W, 7-1, year: 2017
W, 2-1, year: 2017
W, 3-1, year: 2017
W, 3-2, year: 2017
W, 2-0, year: 2017
L, 0-2, year: 2017
W, 4-0, year: 2017
L, 1-2, year: 2017
W, 1-0 2OT, year: 2017
L, 0-2, year: 2017
W, 3-1, year: 2018
W, 2-1, year: 2018
W, 1-0, year: 2018
W, 2-1, year: 2018
W, 2-1 (2OT), year: 2018
L, 0-2, year: 2018
L, 0-1, year: 2018
L, 1-2 (OT), year: 2018
W, 4-0, year: 2018
L, 0-2, year: 2018
W, 2-0, year: 2018
T, 0-0 (2OT), year: 2018
W, 1-0 (2OT), year: 2018
W, 3-0, year: 2018
L, 1-2 (2OT), year: 2018
W, 2-1, year: 2018
L, 2-3, year: 2018
L, 2-3, year: 2018
W, 3-1, year: 2018
L, 0-2, year: 2018
W, 1-0, year: 2018
W, 2-0, year: 2018
T, 0-0 (Advance on PKs 5-4), year: 2018
W, 2-0, year: 2018
L, 0-5, year: 2018
W, 3-0, year: 2019
T, 2-2, year: 2019
L, 0-2, year: 2019
T, 1-1, year: 2019
L, 2-3, year: 2019
L, 0-1, year: 2019
L, 0-2, year: 2019
W, 1-0, year: 2019
L, 0-1, year: 2019
L, 0-2, year: 2019
L, 0-2, year: 2019
L, 0-1, year: 2019
W, 1-0, year: 2019
T, 0-0, year: 2019
L, 0-1, year: 2019
L, 0-1, year: 2019
T, 1-1, year: 2019
L, 1-2, year: 2019
W, 1-0, year: 2019
L, 1-4, year: 2019

In [27]:
umn_hist_schedule['opponent'] = opponent_list
umn_hist_schedule['game_full_date'] = date_list
umn_hist_schedule['game_year'] = year_list
umn_hist_schedule['game_result'] = result_list

umn_hist_schedule[['game_date','game_full_date']] = umn_hist_schedule['game_full_date'].str.split("(",expand=True)
umn_hist_schedule[['game_day_of_week','game_time']] = umn_hist_schedule['game_full_date'].str.split(")",expand=True)
umn_hist_schedule[['game_result','game_score']] = umn_hist_schedule['game_result'].str.split(',',expand=True)

In [28]:
umn_hist_schedule

,opponent,game_full_date,game_year,game_result,game_date,game_day_of_week,game_time,game_score
0,South Dakota St.,Wed) 6:00 PM,2012,W,Aug 8,Wed,6:00 PM,4-0
1,Florida State,Fri) 7:00 PM,2012,L,Aug 17,Fri,7:00 PM,2-3
2,South Carolina,Sun) 12:00 PM,2012,W,Aug 19,Sun,12:00 PM,2-1 OT
3,San Diego,Fri) 7:00 PM,2012,L,Aug 24,Fri,7:00 PM,2-3 2OT
4,USC,Sun) 3:00 PM,2012,W,Aug 26,Sun,3:00 PM,4-1
...,...,...,...,...,...,...,...,...
173,Wisconsin,Fri) 5:00 PM BTN+,2019,L,Oct 11,Fri,5:00 PM BTN+,0-1
174,Nebraska,Thu) 4:00 PM,2019,T,Oct 17,Thu,4:00 PM,1-1
175,Iowa,Sun) 1:00 PM BTN+,2019,L,Oct 20,Sun,1:00 PM BTN+,1-2
176,Northwestern,Thu) 6:00 PM BTN,2019,W,Oct 24,Thu,6:00 PM BTN,1-0
177,Illinois,Sun) 1:00 PM BTN+,2019,L,Oct 27,Sun,1:00 PM BTN+,1-4

In [32]:
vs_nebraska