In [147]:
import pandas as pd
import numpy as np

In [112]:
URL = "http://collegepollarchive.com/football/ap/seasons.cfm?appollid=1185"
pd.read_html(URL)

tables = pd.read_html(URL)
print("There are : ",len(tables)," tables")
print("Take look at table 0")
print(tables[9])

There are :  12  tables
Take look at table 0
   Rank Rank.1         Team (FPV)      Conf   Rec     Pts   CP  \
0     1    < 1       Alabama (61)       SEC  13-0  1525.0   *1
1     2    < 3         Ohio State   Big Ten   7-1  1463.0    2
2     3    < 2            Clemson       ACC  10-2  1378.0    3
3     4    < 5          Texas A&M       SEC   9-1  1324.0    4
4     5    < 4         Notre Dame       ACC  10-2  1279.0    5
5     6    < 8           Oklahoma    Big 12   9-2  1243.0    6
6     7   < 11            Georgia       SEC   8-2  1144.0    7
7     8    < 6         Cincinnati       AAC   9-1  1074.0    8
8     9   < 12         Iowa State    Big 12   9-3  1035.0    9
9    10   < 15       Northwestern   Big Ten   7-2   893.0   10
10   11   < 13                BYU       Ind  11-1   862.0   11
11   12    < 7            Indiana   Big Ten   6-2   773.0   13
12   13   < 10            Florida       SEC   8-4   764.0   12
13   14    < 9   Coastal Carolina  Sun Belt  11-1   725.0   14
14   15   < 16          Louisiana  Sun Belt  10-1   664.0   16
15   16   < 17               Iowa   Big Ten   6-2   581.0   15
16   17   < 23            Liberty       Ind  10-1   576.0   18
17   18   < 14     North Carolina       ACC   8-4   532.0   17
18   19   < 20              Texas    Big 12   7-3   485.0   20
19   20   < NR     Oklahoma State    Big 12   8-3   417.0   19
20   21   < 21                USC    Pac-12   5-1   306.0   21
21   22   < 18         Miami (FL)       ACC   8-3   284.0   22
22   23   < NR         Ball State       MAC   7-1   183.0   23
23   24   < 19     San Jose State       MWC   7-1    80.0   24
24   25   < NR            Buffalo       MAC   6-1    51.0   25
25   RV   < NR  Appalachian State  Sun Belt   NaN    41.0   RV
26   RV   < 22              Tulsa       AAC   NaN    35.0   RV
27   RV   < NR               Army       Ind   NaN    24.0   RV
28   RV   < 25             Oregon    Pac-12   NaN    21.0   RV
29   RV   < NR            Memphis       AAC   NaN    12.0   RV
30   RV   < NR                TCU    Big 12   NaN    12.0   NR
31   RV   < NR                UAB     C-USA   NaN    10.0   RV
32   RV   < NR         Washington    Pac-12   NaN    10.0   RV
33   RV   < 24           NC State       ACC   NaN     7.0   RV
34   RV   < NR             Nevada       MWC   NaN     7.0   RV
35   RV   < NR          Wisconsin   Big Ten   NaN     3.0   RV
36   RV   < NR           Marshall     C-USA   NaN     1.0   RV
37   RV   < NR      West Virginia    Big 12   NaN     1.0   RV
38   NR   < NR             Auburn       SEC   NaN     0.0   RV
39   NR   < NR        Boise State       MWC   NaN     0.0   RV
40   NR   < NR           Colorado    Pac-12   NaN     0.0   RV
41   NR   < NR           Kentucky       SEC   NaN     0.0   RV
42   NR   < NR        Mississippi       SEC   NaN     0.0   RV
43   NR   < NR           Missouri       SEC   NaN     0.0   RV
44   NR   < NR                SMU       AAC   NaN     0.0   RV
45   NR   < NR               Utah    Pac-12   NaN     0.0   RV
46  NaN    NaN                NaN       NaN   NaN     NaN  NaN

                                            Last Week  Unnamed: 8  Unnamed: 9  \
0                 W 52-24 N #3 Ohio State (CFP Final)         NaN         NaN
1                    L 52-24 N #1 Alabama (CFP Final)         NaN         NaN
2       L 49-28 N #3 Ohio State (Sugar/CFP Semifinal)         NaN         NaN
3               W 41-27 N #14 North Carolina (Orange)         NaN         NaN
4           L 31-14 N #1 Alabama (Rose/CFP Semifinal)         NaN         NaN
5                      W 55-20 N #10 Florida (Cotton)         NaN         NaN
6                     W 24-21 N #6 Cincinnati (Peach)         NaN         NaN
7                       L 24-21 N #11 Georgia (Peach)         NaN         NaN
8                       W 34-17 N #25 Oregon (Fiesta)         NaN         NaN
9                           W 35-19 N Auburn (Citrus)         NaN         NaN
10                         W 49-23 N UCF (Boca Raton)         NaN         NaN
11                    L 26-20 N Mississippi (Outback)         NaN         NaN
12                     L 55-20 N #8 Oklahoma (Cotton)         NaN         NaN
13    L 37-34 (1OT) N #23 Liberty (FBC Mortgage Cure)         NaN         NaN
14           W 31-24 N UTSA (SERVPRO First Responder)         NaN         NaN
15                                                DNP         NaN         NaN
16  W 37-34 (1OT) N #9 Coastal Carolina (FBC Mortg...         NaN         NaN
17                    L 41-27 N #5 Texas A&M (Orange)         NaN         NaN
18                         W 55-23 N Colorado (Alamo)         NaN         NaN
19                W 37-34 N #18 Miami (FL) (Cheez-It)         NaN         NaN
20                                                DNP         NaN         NaN
21                L 37-34 N Oklahoma State (Cheez-It)         NaN         NaN
22             W 34-13 N #19 San Jose State (Arizona)         NaN         NaN
23                     L 34-13 N Ball State (Arizona)         NaN         NaN
24                       W 17-10 N Marshall (Camelia)         NaN         NaN
25               W 56-28 N North Texas (Myrtle Beach)         NaN         NaN
26         L 28-26 N Mississippi State (Armed Forces)         NaN         NaN
27                  L 24-21 N West Virginia (Liberty)         NaN         NaN
28                  L 34-17 N #12 Iowa State (Fiesta)         NaN         NaN
29            W 25-10 N Florida Atlantic (Montgomery)         NaN         NaN
30                                                DNP         NaN         NaN
31                                                DNP         NaN         NaN
32                                                DNP         NaN         NaN
33                         L 23-21 N Kentucky (Gator)         NaN         NaN
34             W 38-27 N Tulane (Famous Idaho Potato)         NaN         NaN
35                W 42-28 N Wake Forest (Duke's Mayo)         NaN         NaN
36                        L 17-10 N Buffalo (Camelia)         NaN         NaN
37                           W 24-21 N Army (Liberty)         NaN         NaN
38                L 35-19 N #15 Northwestern (Citrus)         NaN         NaN
39                                                DNP         NaN         NaN
40                        L 55-23 N #20 Texas (Alamo)         NaN         NaN
41                     W 23-21 N #24 NC State (Gator)         NaN         NaN
42                     W 26-20 N #7 Indiana (Outback)         NaN         NaN
43                                                DNP         NaN         NaN
44                                                DNP         NaN         NaN
45                                                DNP         NaN         NaN
46                                                NaN         NaN         NaN

    Unnamed: 10  Unnamed: 11  Unnamed: 12
0           NaN          NaN          NaN
1           NaN          NaN          NaN
2           NaN          NaN          NaN
3           NaN          NaN          NaN
4           NaN          NaN          NaN
5           NaN          NaN          NaN
6           NaN          NaN          NaN
7           NaN          NaN          NaN
8           NaN          NaN          NaN
9           NaN          NaN          NaN
10          NaN          NaN          NaN
11          NaN          NaN          NaN
12          NaN          NaN          NaN
13          NaN          NaN          NaN
14          NaN          NaN          NaN
15          NaN          NaN          NaN
16          NaN          NaN          NaN
17          NaN          NaN          NaN
18          NaN          NaN          NaN
19          NaN          NaN          NaN
20          NaN          NaN          NaN
21          NaN          NaN          NaN
22          NaN          NaN          NaN
23          NaN          NaN          NaN
24          NaN          NaN          NaN
25          NaN          NaN          NaN
26          NaN          NaN          NaN
27          NaN          NaN          NaN
28          NaN          NaN          NaN
29          NaN          NaN          NaN
30          NaN          NaN          NaN
31          NaN          NaN          NaN
32          NaN          NaN          NaN
33          NaN          NaN          NaN
34          NaN          NaN          NaN
35          NaN          NaN          NaN
36          NaN          NaN          NaN
37          NaN          NaN          NaN
38          NaN          NaN          NaN
39          NaN          NaN          NaN
40          NaN          NaN          NaN
41          NaN          NaN          NaN
42          NaN          NaN          NaN
43          NaN          NaN          NaN
44          NaN          NaN          NaN
45          NaN          NaN          NaN
46          NaN          NaN          NaN

In [113]:
poll_table = tables[9]

In [114]:
poll_table = poll_table[['Rank',"Rank.1","Team (FPV)"]]

In [73]:
poll_table['final_rank'] = poll_table['Rank']
poll_table = poll_table[:10]
poll_table[['dummy','preseason_rank']] = poll_table['Rank.1'].str.split('<',expand=True)

<ipython-input-73-175f440cefd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poll_table['final_rank'] = poll_table['Rank']

In [74]:
poll_table = poll_table[['Team (FPV)','final_rank','preseason_rank']]
poll_table['final_rank'] = poll_table['final_rank'].astype(int)
poll_table['preseason_rank'] = poll_table['preseason_rank'].astype(int)

In [75]:
poll_table

     Team (FPV)  final_rank  preseason_rank
0  Alabama (61)           1               1
1    Ohio State           2               3
2       Clemson           3               2
3     Texas A&M           4               5
4    Notre Dame           5               4
5      Oklahoma           6               8
6       Georgia           7              11
7    Cincinnati           8               6
8    Iowa State           9              12
9  Northwestern          10              15

In [76]:
poll_table.dtypes

Team (FPV)        object
final_rank         int64
preseason_rank     int64
dtype: object

In [83]:
poll_table.loc[poll_table['preseason_rank'] <= 10, 'top_ten'] = 'True'
poll_table.loc[poll_table['preseason_rank'] > 10, 'top_ten'] = 'False'

In [84]:
poll_table

     Team (FPV)  final_rank  preseason_rank top_ten
0  Alabama (61)           1               1    True
1    Ohio State           2               3    True
2       Clemson           3               2    True
3     Texas A&M           4               5    True
4    Notre Dame           5               4    True
5      Oklahoma           6               8    True
6       Georgia           7              11   False
7    Cincinnati           8               6    True
8    Iowa State           9              12   False
9  Northwestern          10              15   False

## All seasons

In [48]:
import pandas as pd

In [150]:
base_url = "http://collegepollarchive.com/football/ap/seasons.cfm?seasonid="
pd.read_html(base_url)
urls = []
for year in range(1990,2021):
    url = base_url + str(year)
    urls.append(url)
print(urls)

['http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1990', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1991', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1992', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1993', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1994', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1995', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1996', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1997', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1998', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=1999', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2000', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2001', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2002', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2003', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2004', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2005', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2006', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2007', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2008', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2009', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2010', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2011', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2012', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2013', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2014', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2015', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2016', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2017', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2018', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2019', 'http://collegepollarchive.com/football/ap/seasons.cfm?seasonid=2020']

In [151]:
stayed_list = []
same_list = []
print("Teams that were in the AP Top Ten preseason and final poll")
for url in urls:
    tables = pd.read_html(url)
    table = tables[9]
    
    poll_table = table[['Rank',"Rank.1","Team (FPV)"]]
    poll_table = poll_table[:11]
    
    # format table
    poll_table['final_rank'] = poll_table['Rank']
    poll_table[['dummy','preseason_rank']] = poll_table['Rank.1'].str.split('<',expand=True)
    
    # format table cont.
    poll_table = poll_table[['Team (FPV)','final_rank','preseason_rank']]
    poll_table['final_rank'] = poll_table['final_rank'].astype(int)
    poll_table['preseason_rank'] = poll_table['preseason_rank'].astype(int)
    
    # Stayed in Top Ten Column
    poll_table.loc[poll_table['preseason_rank'] <= 10, 'top_ten'] = 1
    poll_table.loc[poll_table['preseason_rank'] > 10, 'top_ten'] = 0
    total_stayed = sum(poll_table['top_ten'])
    stayed_list.append(total_stayed)
    
    # Same rank column
    poll_table.loc[poll_table['preseason_rank'] == poll_table['final_rank'], 'same'] = 1
    poll_table.loc[poll_table['preseason_rank'] != poll_table['final_rank'], 'same'] = 0
    total_same = sum(poll_table['same'])
    same_list.append(total_same)
    
    print(url[-4:],"Stayed in top ten: ", sum(poll_table['top_ten']), "| Kept same ranking: ", sum(poll_table['same']))

Teams that were in the AP Top Ten preseason and final poll
1990 Stayed in top ten:  9.0 | Kept same ranking:  2.0
1991 Stayed in top ten:  8.0 | Kept same ranking:  2.0
1992 Stayed in top ten:  9.0 | Kept same ranking:  2.0
1993 Stayed in top ten:  8.0 | Kept same ranking:  2.0
1994 Stayed in top ten:  9.0 | Kept same ranking:  4.0
1995 Stayed in top ten:  9.0 | Kept same ranking:  2.0
1996 Stayed in top ten:  9.0 | Kept same ranking:  5.0
1997 Stayed in top ten:  9.0 | Kept same ranking:  3.0
1998 Stayed in top ten:  10.0 | Kept same ranking:  1.0
1999 Stayed in top ten:  9.0 | Kept same ranking:  4.0
2000 Stayed in top ten:  9.0 | Kept same ranking:  3.0
2001 Stayed in top ten:  9.0 | Kept same ranking:  2.0
2002 Stayed in top ten:  9.0 | Kept same ranking:  0.0
2003 Stayed in top ten:  7.0 | Kept same ranking:  3.0
2004 Stayed in top ten:  9.0 | Kept same ranking:  1.0
2005 Stayed in top ten:  7.0 | Kept same ranking:  2.0
2006 Stayed in top ten:  10.0 | Kept same ranking:  0.0
2007 Stayed in top ten:  8.0 | Kept same ranking:  0.0
2008 Stayed in top ten:  9.0 | Kept same ranking:  1.0
2009 Stayed in top ten:  9.0 | Kept same ranking:  2.0
2010 Stayed in top ten:  8.0 | Kept same ranking:  1.0
2011 Stayed in top ten:  10.0 | Kept same ranking:  2.0
2012 Stayed in top ten:  8.0 | Kept same ranking:  1.0
2013 Stayed in top ten:  8.0 | Kept same ranking:  2.0
2014 Stayed in top ten:  9.0 | Kept same ranking:  0.0
2015 Stayed in top ten:  8.0 | Kept same ranking:  0.0
2016 Stayed in top ten:  10.0 | Kept same ranking:  1.0
2017 Stayed in top ten:  9.0 | Kept same ranking:  1.0
2018 Stayed in top ten:  8.0 | Kept same ranking:  1.0
2019 Stayed in top ten:  8.0 | Kept same ranking:  3.0
2020 Stayed in top ten:  7.0 | Kept same ranking:  1.0

In [152]:
r = np.corrcoef(stayed_list, same_list)
r

array([[ 1.        , -0.02637394],
       [-0.02637394,  1.        ]])

In [137]:
poll_list = []
print("Teams that had same AP Top Ten preseason and final poll")
for url in urls:
    tables = pd.read_html(url)
    table = tables[9]
    
    poll_table = table[['Rank',"Rank.1","Team (FPV)"]]
    poll_table = poll_table[:11]
    
    # format table
    poll_table['final_rank'] = poll_table['Rank']
    poll_table[['dummy','preseason_rank']] = poll_table['Rank.1'].str.split('<',expand=True)
    
    # format table cont.
    poll_table = poll_table[['Team (FPV)','final_rank','preseason_rank']]
    poll_table['final_rank'] = poll_table['final_rank'].astype(int)
    poll_table['preseason_rank'] = poll_table['preseason_rank'].astype(int)
    
    # New Column
    poll_table.loc[poll_table['preseason_rank'] == poll_table['final_rank'], 'same'] = 1
    poll_table.loc[poll_table['preseason_rank'] != poll_table['final_rank'], 'same'] = 0
    print(url[-4:], sum(poll_table['same']))

Teams that had same AP Top Ten preseason and final poll
2000 3.0
2001 2.0
2002 0.0
2003 3.0
2004 1.0
2005 2.0
2006 0.0
2007 0.0
2008 1.0
2009 2.0
2010 1.0
2011 2.0
2012 1.0
2013 2.0
2014 0.0
2015 0.0
2016 1.0
2017 1.0
2018 1.0
2019 3.0
2020 1.0

In [133]:
poll_table

      Team (FPV)  final_rank  preseason_rank  top_ten
0   Alabama (61)           1               1      1.0
1     Ohio State           2               3      1.0
2        Clemson           3               2      1.0
3      Texas A&M           4               5      1.0
4     Notre Dame           5               4      1.0
5       Oklahoma           6               8      1.0
6        Georgia           7              11      0.0
7     Cincinnati           8               6      1.0
8     Iowa State           9              12      0.0
9   Northwestern          10              15      0.0
10           BYU          11              13      0.0

In [71]:
poll_table = tables[9]

In [72]:
poll_table = poll_table[['Rank',"Rank.1","Team (FPV)"]]

In [73]:
poll_table['final_rank'] = poll_table['Rank']
poll_table = poll_table[:10]
poll_table[['dummy','preseason_rank']] = poll_table['Rank.1'].str.split('<',expand=True)

<ipython-input-73-175f440cefd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poll_table['final_rank'] = poll_table['Rank']

In [74]:
poll_table = poll_table[['Team (FPV)','final_rank','preseason_rank']]
poll_table['final_rank'] = poll_table['final_rank'].astype(int)
poll_table['preseason_rank'] = poll_table['preseason_rank'].astype(int)

In [75]:
poll_table

     Team (FPV)  final_rank  preseason_rank
0  Alabama (61)           1               1
1    Ohio State           2               3
2       Clemson           3               2
3     Texas A&M           4               5
4    Notre Dame           5               4
5      Oklahoma           6               8
6       Georgia           7              11
7    Cincinnati           8               6
8    Iowa State           9              12
9  Northwestern          10              15

In [76]:
poll_table.dtypes

Team (FPV)        object
final_rank         int64
preseason_rank     int64
dtype: object

In [83]:
poll_table.loc[poll_table['preseason_rank'] <= 10, 'top_ten'] = 'True'
poll_table.loc[poll_table['preseason_rank'] > 10, 'top_ten'] = 'False'

In [84]:
poll_table

     Team (FPV)  final_rank  preseason_rank top_ten
0  Alabama (61)           1               1    True
1    Ohio State           2               3    True
2       Clemson           3               2    True
3     Texas A&M           4               5    True
4    Notre Dame           5               4    True
5      Oklahoma           6               8    True
6       Georgia           7              11   False
7    Cincinnati           8               6    True
8    Iowa State           9              12   False
9  Northwestern          10              15   False